runtime: nodejs20
env: standard
instance_class: F1
service: frontend

automatic_scaling:
  max_instances: 2
  min_instances: 0
  min_idle_instances: 0
  max_idle_instances: 1

handlers:
  - url: /_next/static
    static_dir: .next/static
    expiration: 1d
  
  - url: /.*
    script: auto
    secure: always

env_variables:
  NODE_ENV: production